cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy
build:
  stage: build
  script:
    - echo "Building deploy package"
    - npm install
    - npm run build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
          
deploy-dev:
  stage: deploy
  script:
    - echo "Deploying to server"
    - cp -rv build/* /var/www/html/dev-fe/
    - echo "Deployed"
  environment:
    name: development
    url: https://dev-fe.jrvis.id
  only:
    - development