cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:13.11
  script:
    - npm install
    - CI=false npm run build

deploy_dev:
  stage: deploy
  image: alpine:3.10
  only:
  - dev
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/* deploy@$SSH_SERVER_DEV.com:/var/www/$SSH_SERVER_DEV/current/public