cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  artifacts:
    paths:
      - build
  image: node
  script:
    - npm ci
    - npm run generate-build-meta
    - npm run build
  stage: build

deploy-prd:
  image: alpine:3.10
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/* deploy@$SSH_SERVER_PRD:/home/normal/public_html/$URL_PRD/
  stage: deploy
