// Alert
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

// Login
export const ADD_LOGIN = "ADD_LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"

// Customer
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const ADD_CUSTOMER_ERROR = "ADD_CUSTOMER_ERROR"
export const EDIT_CUSTOMER = "EDIT_CUSTOMER"
export const GET_CUSTOMER = "GET_CUSTOMER"
export const GET_DETAIL_CUSTOMER = "GET_DETAIL_CUSTOMER"

// Dashboard
export const GET_PRODUCT_DASHBOARD = "GET_PRODUCT_DASHBOARD"

// Purchase Order
export const GET_PURCHASE_ORDER = "GET_PURCHASE_ORDER"
export const GET_PURCHASE_ORDER_DETAIL = "GET_PURCHASE_ORDER_DETAIL"

export const ADD_PURCHASE_ORDER = "ADD_PURCHASE_ORDER"
export const ADD_PURCHASE_ORDER_DETAIL = "ADD_PURCHASE_ORDER_DETAIL"