// Alert
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

// Login
export const ADD_LOGIN = "ADD_LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"

// Profile
export const GET_PROFILE = "GET_PROFILE"
export const EDIT_PROFILE = "EDIT_PROFILE"

// Customer
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS"
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED"
export const ADD_CUSTOMER_ERROR = "ADD_CUSTOMER_ERROR"

export const EDIT_CUSTOMER = "EDIT_CUSTOMER"
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS"
export const EDIT_CUSTOMER_FAILED = "EDIT_CUSTOMER_FAILED"

export const GET_CUSTOMER = "GET_CUSTOMER"
export const GET_DETAIL_CUSTOMER = "GET_DETAIL_CUSTOMER"
export const GET_SEARCH_CUSTOMER = "GET_SEARCH_CUSTOMER"
export const GET_SEARCH_CUSTOMER_BUYBACK = "GET_SEARCH_CUSTOMER_BUYBACK"

export const GET_CUSTOMER_V2 = "GET_CUSTOMER_V2"
export const GET_SEARCH_CUSTOMER_CLEAR = "GET_SEARCH_CUSTOMER_CLEAR"


// Dashboard
export const GET_PRODUCT_DASHBOARD = "GET_PRODUCT_DASHBOARD"
export const GET_PRODUCT_BUYBACK_DASHBOARD = "GET_PRODUCT_BUYBACK_DASHBOARD"
export const GET_CARD_STATS = "GET_CARD_STATS"
export const GET_NET_INCOME = "GET_NET_INCOME"
export const GET_GRAFIK_COST = "GET_GRAFIK_COST"
export const GET_GOLD_PRICE = "GET_GOLD_PRICE"
export const GET_TRANSACTION_SALES = "GET_TRANSACTION_SALES"

export const GET_GRAFIK_STOCK = "GET_GRAFIK_STOCK"
export const GET_GRAFIK_STOCK2 = "GET_GRAFIK_STOCK2"
export const GET_GRAFIK_STOCK3 = "GET_GRAFIK_STOCK3"
export const GET_GRAFIK_STOCK4 = "GET_GRAFIK_STOCK4"
export const GET_GRAFIK_STOCK5 = "GET_GRAFIK_STOCK5"
export const GET_GRAFIK_STOCK6 = "GET_GRAFIK_STOCK6"

export const GET_GRAFIK_HPP = "GET_GRAFIK_HPP"

// Purchase Order
export const GET_PURCHASE_ORDER = "GET_PURCHASE_ORDER"
export const GET_PURCHASE_ORDER_DETAIL = "GET_PURCHASE_ORDER_DETAIL"

export const ADD_PURCHASE_ORDER = "ADD_PURCHASE_ORDER"
export const ADD_PURCHASE_ORDER_DETAIL = "ADD_PURCHASE_ORDER_DETAIL"

export const DELETE_PURCHASE_ORDER_DETAIL = "DELETE_PURCHASE_ORDER_DETAIL"

export const GET_PRODUCT_PO = "GET_PRODUCT_PO"

export const UPDATE_PURCHASE_ORDER_DONE = "UPDATE_PURCHASE_ORDER_DONE"

// Cart
export const GET_CART = "GET_CART"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"
export const DELETE_CART_ALL_ITEM = "DELETE_CART_ALL_ITEM"

// Payment
export const PURCHASE_ITEM_PAY = "PURCHASE_ITEM_PAY"
export const PURCHASE_ITEM_PAY_ERROR = "PURCHASE_ITEM_PAY_ERROR"

// Transaction
export const GET_TRANSACTION = "GET_TRANSACTION"
export const GET_SEARCH_TRANSACTION = "GET_SEARCH_TRANSACTION"
export const GET_DETAIL_TRANSACTION = "GET_DETAIL_TRANSACTION"

// First Balancing
export const GET_FIRST_BALANCE = "GET_FIRST_BALANCE"
export const ADD_FIRST_BALANCE = "ADD_FIRST_BALANCE"
export const ADD_FIRST_BALANCE_ERROR = "ADD_FIRST_BALANCE_ERROR"

// Product
export const GET_PRODUCT = "GET_PRODUCT"

// Stock Opname
export const GET_STOCK_OPNAME = "GET_STOCK_OPNAME"
export const BALANCING_STOCK_OPNAME = "BALANCING_STOCK_OPNAME"

// Transaksi Buyback
// Cart
export const GET_CART_BUYBACK = "GET_CART_BUYBACK"
export const ADD_TO_CART_BUYBACK = "ADD_TO_CART_BUYBACK"
export const DELETE_CART_ITEM_BUYBACK = "DELETE_CART_ITEM_BUYBACK"
export const DELETE_CART_ALL_ITEM_BUYBACK = "DELETE_CART_ALL_ITEM_BUYBACK"

// Payment
export const PURCHASE_ITEM_PAY_BUYBACK = "PURCHASE_ITEM_PAY_BUYBACK"
export const PURCHASE_ITEM_PAY_ERROR_BUYBACK = "PURCHASE_ITEM_PAY_ERROR_BUYBACK"

export const GET_TRANSACTION_BUYBACK = "GET_TRANSACTION_BUYBACK"
export const GET_SEARCH_TRANSACTION_BUYBACK = "GET_SEARCH_TRANSACTION_BUYBACK"
export const GET_DETAIL_TRANSACTION_BUYBACK = "GET_DETAIL_TRANSACTION_BUYBACK"

// Stock History
export const GET_STOCK_HISTORY = "GET_STOCK_HISTORY"
export const GET_STOCK_HISTORY_DETAIL = "GET_STOCK_HISTORY_DETAIL"

// Other Purchase Order
export const GET_OTHER_PURCHASE_ORDER = "GET_OTHER_PURCHASE_ORDER"
export const ADD_OTHER_PURCHASE_ORDER = "ADD_OTHER_PURCHASE_ORDER"

export const GET_OTHER_PURCHASE_ORDER_DETAIL = "GET_OTHER_PURCHASE_ORDER_DETAIL"
export const ADD_OTHER_PURCHASE_ORDER_DETAIL = "ADD_OTHER_PURCHASE_ORDER_DETAIL"
export const DELETE_OTHER_PURCHASE_ORDER_DETAIL = "DELETE_OTHER_PURCHASE_ORDER_DETAIL"
export const UPDATE_OTHER_PURCHASE_ORDER_DETAIL = "UPDATE_OTHER_PURCHASE_ORDER_DETAIL"
