export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_DIALOG_BOX = 'SET_DIALOG_BOX';
export const REMOVE_DIALOG_BOX = 'REMOVE_DIALOG_BOX';

export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS"
export const GET_TEAM_START = "GET_TEAM_START"
export const GET_TEAM_FAIL = "GET_TEAM_FAIL"

// Province
export const GET_PROVINCE = "GET_PROVINCE"
export const GET_CITY = "GET_CITY"
export const GET_DISTRICT = "GET_DISTRICT"
export const GET_VILLAGE = "GET_VILLAGE"

// Dashboard
    // Get Total User
        export const GET_DASHBOARD_TOTAL_USER_START = "GET_DASHBOARD_TOTAL_USER_START"
        export const GET_DASHBOARD_TOTAL_USER_SUCCESS = "GET_DASHBOARD_TOTAL_USER_SUCCESS"
        export const GET_DASHBOARD_TOTAL_USER_FAIL = "GET_DASHBOARD_TOTAL_USER_FAIL"

        export const GET_DASHBOARD_TOTAL_TRANSACTION_START = "GET_DASHBOARD_TOTAL_TRANSACTION_START"
        export const GET_DASHBOARD_TOTAL_TRANSACTION_SUCCESS = "GET_DASHBOARD_TOTAL_TRANSACTION_SUCCESS"
        export const GET_DASHBOARD_TOTAL_TRANSACTION_FAIL = "GET_DASHBOARD_TOTAL_TRANSACTION_FAIL"

        export const GET_DASHBOARD_GRAFIK_INCOME_START = "GET_DASHBOARD_GRAFIK_INCOME_START"
        export const GET_DASHBOARD_GRAFIK_INCOME_SUCCESS = "GET_DASHBOARD_GRAFIK_INCOME_SUCCESS"
        export const GET_DASHBOARD_GRAFIK_INCOME_FAIL = "GET_DASHBOARD_GRAFIK_INCOME_FAIL"

        export const GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_START = "GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_START"
        export const GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_SUCCESS = "GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_SUCCESS"
        export const GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_FAIL = "GET_DASHBOARD_GRAFIK_TRANSACTION_MONTHLY_FAIL"

        export const GET_DASHBOARD_PRODUCT_BESTSELLER_START = "GET_DASHBOARD_PRODUCT_BESTSELLER_START"
        export const GET_DASHBOARD_PRODUCT_BESTSELLER_SUCCESS = "GET_DASHBOARD_PRODUCT_BESTSELLER_SUCCESS"
        export const GET_DASHBOARD_PRODUCT_BESTSELLER_FAIL = "GET_DASHBOARD_PRODUCT_BESTSELLER_FAIL"

        export const GET_DASHBOARD_POPULAR_PRODUCT_START = "GET_DASHBOARD_POPULAR_PRODUCT_START"
        export const GET_DASHBOARD_POPULAR_PRODUCT_SUCCESS = "GET_DASHBOARD_POPULAR_PRODUCT_SUCCESS"
        export const GET_DASHBOARD_POPULAR_PRODUCT_FAIL = "GET_DASHBOARD_POPULAR_PRODUCT_FAIL"

        export const GET_DASHBOARD_INTERESTED_PRODUCT_START = "GET_DASHBOARD_INTERESTED_PRODUCT_START"
        export const GET_DASHBOARD_INTERESTED_PRODUCT_SUCCESS = "GET_DASHBOARD_INTERESTED_PRODUCT_SUCCESS"
        export const GET_DASHBOARD_INTERESTED_PRODUCT_FAIL = "GET_DASHBOARD_INTERESTED_PRODUCT_FAIL"

        export const GET_DASHBOARD_RESELLER_ACTIVE_START = "GET_DASHBOARD_RESELLER_ACTIVE_START"
        export const GET_DASHBOARD_RESELLER_ACTIVE_SUCCESS = "GET_DASHBOARD_RESELLER_ACTIVE_SUCCESS"
        export const GET_DASHBOARD_RESELLER_ACTIVE_FAIL = "GET_DASHBOARD_RESELLER_ACTIVE_FAIL"


// Master
    // Warehouse
    export const GET_WAREHOUSE = "GET_WAREHOUSE"

    export const ADD_WAREHOUSE_START = "ADD_WAREHOUSE_START"
    export const ADD_WAREHOUSE_SUCCESS = "ADD_WAREHOUSE_SUCCESS"
    export const ADD_WAREHOUSE_FAIL = "ADD_WAREHOUSE_FAIL"

    // Category
    export const GET_CATEGORY = "GET_CATEGORY"
    export const GET_CATEGORY_PAGINATION = "GET_CATEGORY_PAGINATION"

    export const GET_DETAIL_CATEGORY_START = "GET_DETAIL_CATEGORY_START"
    export const GET_DETAIL_CATEGORY_SUCCESS = "GET_DETAIL_CATEGORY_SUCCESS"
    export const GET_DETAIL_CATEGORY_FAIL = "GET_DETAIL_CATEGORY_FAIL"

    export const ADD_CATEGORY_START = "ADD_CATEGORY_START"
    export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
    export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"

    export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START"
    export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
    export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL"

    export const UPLOAD_CATEGORY_IMAGE_START = "UPLOAD_CATEGORY_IMAGE_START"
    export const UPLOAD_CATEGORY_IMAGE_SUCCESS = "UPLOAD_CATEGORY_IMAGE_SUCCESS"
    export const UPLOAD_CATEGORY_IMAGE_FAIL = "UPLOAD_CATEGORY_IMAGE_FAIL"

    export const UPLOAD_CATEGORY_IMAGE_EDIT_START = "UPLOAD_CATEGORY_IMAGE_EDIT_START"
    export const UPLOAD_CATEGORY_IMAGE_EDIT_SUCCESS = "UPLOAD_CATEGORY_IMAGE_EDIT_SUCCESS"
    export const UPLOAD_CATEGORY_IMAGE_EDIT_FAIL = "UPLOAD_CATEGORY_IMAGE_EDIT_FAIL"

    export const ON_CLEAR_UPLOAD_CATEGORY_IMAGE = "ON_CLEAR_UPLOAD_CATEGORY_IMAGE"

    export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START"
    export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
    export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL"

    export const DELETE_IMAGE_CATEGORY = "DELETE_IMAGE_CATEGORY"

    export const EDIT_DELETE_IMAGE_CATEGORY_START = 'EDIT_DELETE_IMAGE_CATEGORY_START';
    export const EDIT_DELETE_IMAGE_CATEGORY_SUCCESS = 'EDIT_DELETE_IMAGE_CATEGORY_SUCCESS';
    export const EDIT_DELETE_IMAGE_CATEGORY_FAIL = 'EDIT_DELETE_IMAGE_CATEGORY_FAIL';

    // Sub Category
    export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

// Product
    export const GET_PRODUCT_START = "GET_PRODUCT_START"
    export const GET_PRODUCT = "GET_PRODUCT"

    export const GET_PRODUCT_DETAIL_START = "GET_PRODUCT_DETAIL_START"
    export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"

    export const ADD_PRODUCT_START = "ADD_PRODUCT_START"
    export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
    export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

    export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START"
    export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
    export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

    export const UPLOAD_PRODUCT_IMAGE_START = "UPLOAD_PRODUCT_IMAGE_START"
    export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS"
    export const UPLOAD_PRODUCT_IMAGE_FAIL = "UPLOAD_PRODUCT_IMAGE_FAIL"
    
    export const UPLOAD_PRODUCT_IMAGE_EDIT_START = "UPLOAD_PRODUCT_IMAGE_EDIT_START"
    export const UPLOAD_PRODUCT_IMAGE_EDIT_SUCCESS = "UPLOAD_PRODUCT_IMAGE_EDIT_SUCCESS"
    export const UPLOAD_PRODUCT_IMAGE_EDIT_FAIL = "UPLOAD_PRODUCT_IMAGE_EDIT_FAIL"

    export const ON_CLEAR_UPLOAD_IMAGE = "ON_CLEAR_UPLOAD_IMAGE"

    export const DELETE_IMAGE_PRODUCT = "DELETE_IMAGE_PRODUCT"

    export const EDIT_DELETE_IMAGE_PRODUCT_START = 'EDIT_DELETE_IMAGE_PRODUCT_START';
    export const EDIT_DELETE_IMAGE_PRODUCT_SUCCESS = 'EDIT_DELETE_IMAGE_PRODUCT_SUCCESS';
    export const EDIT_DELETE_IMAGE_PRODUCT_FAIL = 'EDIT_DELETE_IMAGE_PRODUCT_FAIL';

    // Collection
        // List
        export const GET_PRODUCT_COLLECTION_START = "GET_PRODUCT_COLLECTION_START"
        export const GET_PRODUCT_COLLECTION = "GET_PRODUCT_COLLECTION"
        export const GET_PRODUCT_COLLECTION_FAIL = "GET_PRODUCT_COLLECTION_FAIL"

        // Detail
        export const GET_DETAIL_PRODUCT_COLLECTION_START = "GET_DETAIL_PRODUCT_COLLECTION_START"
        export const GET_DETAIL_PRODUCT_COLLECTION = "GET_DETAIL_PRODUCT_COLLECTION"
        export const GET_DETAIL_PRODUCT_COLLECTION_FAIL = "GET_DETAIL_PRODUCT_COLLECTION_FAIL"

        // Add Product
        export const ADD_PRODUCT_COLLECTION_START = "ADD_PRODUCT_COLLECTION_START"
        export const ADD_PRODUCT_COLLECTION_SUCCESS = "ADD_PRODUCT_COLLECTION_SUCCESS"
        export const ADD_PRODUCT_COLLECTION_FAIL = "ADD_PRODUCT_COLLECTION_FAIL"

            // Upload Product Collection Image
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_START = "UPLOAD_PRODUCT_COLLECTION_IMAGE_START"
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_SUCCESS = "UPLOAD_PRODUCT_COLLECTION_IMAGE_SUCCESS"
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_FAIL = "UPLOAD_PRODUCT_COLLECTION_IMAGE_FAIL"

            // Upload Product Collection Image Edit
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_START = "UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_START"
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_SUCCESS = "UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_SUCCESS"
            export const UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_FAIL = "UPLOAD_PRODUCT_COLLECTION_IMAGE_EDIT_FAIL"

            // Upload Product Collection List
            export const UPLOAD_PRODUCT_COLLECTION_LIST_START = "UPLOAD_PRODUCT_COLLECTION_LIST_START"
            export const UPLOAD_PRODUCT_COLLECTION_LIST_SUCCESS = "UPLOAD_PRODUCT_COLLECTION_LIST_SUCCESS"
            export const UPLOAD_PRODUCT_COLLECTION_LIST_FAIL = "UPLOAD_PRODUCT_COLLECTION_LIST_FAIL"

            // Upload Product Collection Edit
            export const UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_START = "UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_START"
            export const UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_SUCCESS = "UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_SUCCESS"
            export const UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_FAIL = "UPLOAD_PRODUCT_COLLECTION_LIST_EDIT_FAIL"

            // Update Product Collection
            export const UPDATE_PRODUCT_COLLECTION_START = "UPDATE_PRODUCT_COLLECTION_START"
            export const UPDATE_PRODUCT_COLLECTION_SUCCESS = "UPDATE_PRODUCT_COLLECTION_SUCCESS"
            export const UPDATE_PRODUCT_COLLECTION_FAIL = "UPDATE_PRODUCT_COLLECTION_FAIL"

            export const DELETE_PRODUCT_COLLECTION_LIST = "DELETE_PRODUCT_COLLECTION_LIST"

            export const ON_CLEAR_UPLOAD_IMAGE_COLLECTION = "ON_CLEAR_UPLOAD_IMAGE_COLLECTION"
            export const ON_CLEAR_UPLOAD_PRODUCT_COLLECTION_LIST = "ON_CLEAR_UPLOAD_PRODUCT_COLLECTION_LIST"

            export const DELETE_IMAGE_PRODUCT_COLLECTION = "DELETE_IMAGE_PRODUCT_COLLECTION"

            // Delete Product on Edit Collection
            export const DELETE_EDIT_PRODUCT_COLLECTION_LIST_START = "DELETE_EDIT_PRODUCT_COLLECTION_LIST_START"
            export const DELETE_EDIT_PRODUCT_COLLECTION_LIST_SUCCESS = "DELETE_EDIT_PRODUCT_COLLECTION_LIST_SUCCESS"
            export const DELETE_EDIT_PRODUCT_COLLECTION_LIST_FAIL = "DELETE_EDIT_PRODUCT_COLLECTION_LIST_FAIL"
            

// Payment Confirmation
    export const GET_PAYMENT_CONFIRMATION_START = "GET_PAYMENT_CONFIRMATION_START"
    export const GET_PAYMENT_CONFIRMATION = "GET_PAYMENT_CONFIRMATION"
    export const GET_PAYMENT_CONFIRMATION_FAIL = "GET_PAYMENT_CONFIRMATION_FAIL"

    export const UPDATE_STATUS_CONFIRMATION_START = "UPDATE_STATUS_CONFIRMATION_START"
    export const UPDATE_STATUS_CONFIRMATION_SUCCESS = "UPDATE_STATUS_CONFIRMATION_SUCCESS"
    export const UPDATE_STATUS_CONFIRMATION_FAIL = "UPDATE_STATUS_CONFIRMATION_FAIL"

    export const UPDATE_STATUS_SENDING_START = "UPDATE_STATUS_SENDING_START"
    export const UPDATE_STATUS_SENDING_SUCCESS = "UPDATE_STATUS_SENDING_SUCCESS"
    export const UPDATE_STATUS_SENDING_FAIL = "UPDATE_STATUS_SENDING_FAIL"

    export const UPDATE_STATUS_ABORT_START = "UPDATE_STATUS_ABORT_START"
    export const UPDATE_STATUS_ABORT_SUCCESS = "UPDATE_STATUS_ABORT_SUCCESS"
    export const UPDATE_STATUS_ABORT_FAIL = "UPDATE_STATUS_ABORT_FAIL"
    
// Settings
    export const GET_TEXT_FOLLOW_UP_WA_START = "GET_TEXT_FOLLOW_UP_WA_START"
    export const GET_TEXT_FOLLOW_UP_WA_SUCCESS = "GET_TEXT_FOLLOW_UP_WA_SUCCESS"
    export const GET_TEXT_FOLLOW_UP_WA_FAIL = "GET_TEXT_FOLLOW_UP_WA_FAIL"

    export const GET_TEXT_TRANSLATE_WA_START = "GET_TEXT_TRANSLATE_WA_START"
    export const GET_TEXT_TRANSLATE_WA_SUCCESS = "GET_TEXT_TRANSLATE_WA_SUCCESS"
    export const GET_TEXT_TRANSLATE_WA_FAIL = "GET_TEXT_TRANSLATE_WA_FAIL"

    export const GET_DETAIL_TEXT_FOLLOW_UP_WA_START = "GET_DETAIL_TEXT_FOLLOW_UP_WA_START"
    export const GET_DETAIL_TEXT_FOLLOW_UP_WA_SUCCESS = "GET_DETAIL_TEXT_FOLLOW_UP_WA_SUCCESS"
    export const GET_DETAIL_TEXT_FOLLOW_UP_WA_FAIL = "GET_DETAIL_TEXT_FOLLOW_UP_WA_FAIL"

    export const ADD_TEXT_FOLLOW_UP_WA_START = "ADD_TEXT_FOLLOW_UP_WA_START"
    export const ADD_TEXT_FOLLOW_UP_WA_SUCCESS = "ADD_TEXT_FOLLOW_UP_WA_SUCCESS"
    export const ADD_TEXT_FOLLOW_UP_WA_FAIL = "ADD_TEXT_FOLLOW_UP_WA_FAIL"

    export const UPDATE_TEXT_FOLLOW_UP_WA_START = "UPDATE_TEXT_FOLLOW_UP_WA_START"
    export const UPDATE_TEXT_FOLLOW_UP_WA_SUCCESS = "UPDATE_TEXT_FOLLOW_UP_WA_SUCCESS"
    export const UPDATE_TEXT_FOLLOW_UP_WA_FAIL = "UPDATE_TEXT_FOLLOW_UP_WA_FAIL"

    export const DELETE_TEXT_FOLLOW_UP_WA_START = "DELETE_TEXT_FOLLOW_UP_WA_START"
    export const DELETE_TEXT_FOLLOW_UP_WA_SUCCESS = "DELETE_TEXT_FOLLOW_UP_WA_SUCCESS"
    export const DELETE_TEXT_FOLLOW_UP_WA_FAIL = "DELETE_TEXT_FOLLOW_UP_WA_FAIL"

    export const GET_VARIABLE_FOLLOW_UP_WA_START = "GET_VARIABLE_FOLLOW_UP_WA_START"
    export const GET_VARIABLE_FOLLOW_UP_WA_SUCCESS = "GET_VARIABLE_FOLLOW_UP_WA_SUCCESS"
    export const GET_VARIABLE_FOLLOW_UP_WA_FAIL = "GET_VARIABLE_FOLLOW_UP_WA_FAIL"

    export const SEND_WHATSAPP_FOLLOW_UP_START = "SEND_WHATSAPP_FOLLOW_UP_START"
    export const SEND_WHATSAPP_FOLLOW_UP_SUCCESS = "SEND_WHATSAPP_FOLLOW_UP_SUCCESS"
    export const SEND_WHATSAPP_FOLLOW_UP_FAIL = "SEND_WHATSAPP_FOLLOW_UP_FAIL"

    // Banner
    export const GET_BANNER_LIST_START = "GET_BANNER_LIST_START"
    export const GET_BANNER_LIST_SUCCESS = "GET_BANNER_LIST_SUCCESS"
    export const GET_BANNER_LIST_FAIL = "GET_BANNER_LIST_FAIL"

    export const GET_DETAIL_BANNER_LIST_START = "GET_DETAIL_BANNER_LIST_START"
    export const GET_DETAIL_BANNER_LIST_SUCCESS = "GET_DETAIL_BANNER_LIST_SUCCESS"
    export const GET_DETAIL_BANNER_LIST_FAIL = "GET_DETAIL_BANNER_LIST_FAIL"

    export const ADD_BANNER_LIST_START = "ADD_BANNER_LIST_START"
    export const ADD_BANNER_LIST_SUCCESS = "ADD_BANNER_LIST_SUCCESS"
    export const ADD_BANNER_LIST_FAIL = "ADD_BANNER_LIST_FAIL"

    export const UPDATE_BANNER_LIST_START = "UPDATE_BANNER_LIST_START"
    export const UPDATE_BANNER_LIST_SUCCESS = "UPDATE_BANNER_LIST_SUCCESS"
    export const UPDATE_BANNER_LIST_FAIL = "UPDATE_BANNER_LIST_FAIL"

    export const DELETE_BANNER_LIST_START = "DELETE_BANNER_LIST_START"
    export const DELETE_BANNER_LIST_SUCCESS = "DELETE_BANNER_LIST_SUCCESS"
    export const DELETE_BANNER_LIST_FAIL = "DELETE_BANNER_LIST_FAIL"
    
    // Social Media
    export const GET_SOCIAL_MEDIA_LIST_START = "GET_SOCIAL_MEDIA_LIST_START"
    export const GET_SOCIAL_MEDIA_LIST_SUCCESS = "GET_SOCIAL_MEDIA_LIST_SUCCESS"
    export const GET_SOCIAL_MEDIA_LIST_FAIL = "GET_SOCIAL_MEDIA_LIST_FAIL"

    export const GET_DETAIL_SOCIAL_MEDIA_START = "GET_DETAIL_SOCIAL_MEDIA_START"
    export const GET_DETAIL_SOCIAL_MEDIA_SUCCESS = "GET_DETAIL_SOCIAL_MEDIA_SUCCESS"
    export const GET_DETAIL_SOCIAL_MEDIA_FAIL = "GET_DETAIL_SOCIAL_MEDIA_FAIL"

    export const ADD_SOCIAL_MEDIA_START = "ADD_SOCIAL_MEDIA_START"
    export const ADD_SOCIAL_MEDIA_SUCCESS = "ADD_SOCIAL_MEDIA_SUCCESS"
    export const ADD_SOCIAL_MEDIA_FAIL = "ADD_SOCIAL_MEDIA_FAIL"

    export const EDIT_SOCIAL_MEDIA_START = "EDIT_SOCIAL_MEDIA_START"
    export const EDIT_SOCIAL_MEDIA_SUCCESS = "EDIT_SOCIAL_MEDIA_SUCCESS"
    export const EDIT_SOCIAL_MEDIA_FAIL = "EDIT_SOCIAL_MEDIA_FAIL"

    export const UPLOAD_SOCIAL_MEDIA_IMAGE_START = "UPLOAD_SOCIAL_MEDIA_IMAGE_START"
    export const UPLOAD_SOCIAL_MEDIA_IMAGE_SUCCESS = "UPLOAD_SOCIAL_MEDIA_IMAGE_SUCCESS"
    export const UPLOAD_SOCIAL_MEDIA_IMAGE_FAIL = "UPLOAD_SOCIAL_MEDIA_IMAGE_FAIL"

    export const UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_START = "UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_START"
    export const UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_SUCCESS = "UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_SUCCESS"
    export const UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_FAIL = "UPLOAD_SOCIAL_MEDIA_IMAGE_EDIT_FAIL"

    export const DELETE_SOCIAL_MEDIA_START = "DELETE_SOCIAL_MEDIA_START"
    export const DELETE_SOCIAL_MEDIA_SUCCESS = "DELETE_SOCIAL_MEDIA_SUCCESS"
    export const DELETE_SOCIAL_MEDIA_FAIL = "DELETE_SOCIAL_MEDIA_FAIL"

    export const DELETE_IMAGE_SOCIAL_MEDIA = "DELETE_IMAGE_SOCIAL_MEDIA"

    export const ON_CLEAR_UPLOAD_SOCIAL_MEDIA_IMAGE = "ON_CLEAR_UPLOAD_SOCIAL_MEDIA_IMAGE"

// Blog
    export const GET_BLOG_LIST_START = "GET_BLOG_LIST_START"
    export const GET_BLOG_LIST_SUCCESS = "GET_BLOG_LIST_SUCCESS"
    export const GET_BLOG_LIST_FAIL = "GET_BLOG_LIST_FAIL"

    export const GET_DETAIL_BLOG_LIST_START = "GET_DETAIL_BLOG_LIST_START"
    export const GET_DETAIL_BLOG_LIST_SUCCESS = "GET_DETAIL_BLOG_LIST_SUCCESS"
    export const GET_DETAIL_BLOG_LIST_FAIL = "GET_DETAIL_BLOG_LIST_FAIL"

    export const ADD_BLOG_LIST_START = "ADD_BLOG_LIST_START"
    export const ADD_BLOG_LIST_SUCCESS = "ADD_BLOG_LIST_SUCCESS"
    export const ADD_BLOG_LIST_FAIL = "ADD_BLOG_LIST_FAIL"

    export const UPDATE_BLOG_LIST_START = "UPDATE_BLOG_LIST_START"
    export const UPDATE_BLOG_LIST_SUCCESS = "UPDATE_BLOG_LIST_SUCCESS"
    export const UPDATE_BLOG_LIST_FAIL = "UPDATE_BLOG_LIST_FAIL"

    export const DELETE_BLOG_LIST_START = "DELETE_BLOG_LIST_START"
    export const DELETE_BLOG_LIST_SUCCESS = "DELETE_BLOG_LIST_SUCCESS"
    export const DELETE_BLOG_LIST_FAIL = "DELETE_BLOG_LIST_FAIL"

// Notifications
    export const SEND_NOTIFICATION_PRODUCT_START = "SEND_NOTIFICATION_PRODUCT_START"
    export const SEND_NOTIFICATION_PRODUCT_SUCCESS = "SEND_NOTIFICATION_PRODUCT_SUCCESS"
    export const SEND_NOTIFICATION_PRODUCT_FAIL = "SEND_NOTIFICATION_PRODUCT_FAIL"

    export const SEND_NOTIFICATION_PRODUCT_COLLECTION_START = "SEND_NOTIFICATION_PRODUCT_COLLECTION_START"
    export const SEND_NOTIFICATION_PRODUCT_COLLECTION_SUCCESS = "SEND_NOTIFICATION_PRODUCT_COLLECTION_SUCCESS"
    export const SEND_NOTIFICATION_PRODUCT_COLLECTION_FAIL = "SEND_NOTIFICATION_PRODUCT_COLLECTION_FAIL"

    export const SEND_NOTIFICATION_INFORMATION_START = "SEND_NOTIFICATION_INFORMATION_START"
    export const SEND_NOTIFICATION_INFORMATION_SUCCESS = "SEND_NOTIFICATION_INFORMATION_SUCCESS"
    export const SEND_NOTIFICATION_INFORMATION_FAIL = "SEND_NOTIFICATION_INFORMATION_FAIL"