export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_DIALOG_BOX = 'SET_DIALOG_BOX';
export const REMOVE_DIALOG_BOX = 'REMOVE_DIALOG_BOX';

export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS"
export const GET_TEAM_START = "GET_TEAM_START"
export const GET_TEAM_FAIL = "GET_TEAM_FAIL"

export const GET_CUSTOMER_START = "GET_CUSTOMER_START"
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS"
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL"

export const GET_LIST_CUSTOMER_START = "GET_LIST_CUSTOMER_START"
export const GET_LIST_CUSTOMER_SUCCESS = "GET_LIST_CUSTOMER_SUCCESS"
export const GET_LIST_CUSTOMER_FAIL = "GET_LIST_CUSTOMER_FAIL"

export const UPLOAD_CUSTOMER_START = "UPLOAD_CUSTOMER_START"
export const UPLOAD_CUSTOMER_SUCCESS = "UPLOAD_CUSTOMER_SUCCESS"
export const UPLOAD_CUSTOMER_FAIL = "UPLOAD_CUSTOMER_FAIL"

export const GET_LIST_TASK_START = "GET_LIST_TASK_START"
export const GET_LIST_TASK_SUCCESS = "GET_LIST_TASK_SUCCESS"
export const GET_LIST_TASK_FAIL = "GET_LIST_TASK_FAIL"

export const UPLOAD_TASK_START = "UPLOAD_TASK_START"
export const UPLOAD_TASK_SUCCESS = "UPLOAD_TASK_SUCCESS"
export const UPLOAD_TASK_FAIL = "UPLOAD_TASK_FAIL"

export const GET_LIST_REPORT = "GET_LIST_REPORT"
export const EXPORT_REPORT_START = "EXPORT_REPORT_START"
export const EXPORT_REPORT = "EXPORT_REPORT"

export const EXPORT_REPORT_ABSENCE_START = "EXPORT_REPORT_ABSENCE_START"
export const EXPORT_REPORT_ABSENCE = "EXPORT_REPORT_ABSENCE"