export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_DIALOG_BOX = 'SET_DIALOG_BOX';
export const REMOVE_DIALOG_BOX = 'REMOVE_DIALOG_BOX';

export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS"
export const GET_TEAM_START = "GET_TEAM_START"
export const GET_TEAM_FAIL = "GET_TEAM_FAIL"

// Province
export const GET_PROVINCE = "GET_PROVINCE"
export const GET_CITY = "GET_CITY"
export const GET_DISTRICT = "GET_DISTRICT"
export const GET_VILLAGE = "GET_VILLAGE"

// Master
    // Warehouse
    export const GET_WAREHOUSE = "GET_WAREHOUSE"

    export const ADD_WAREHOUSE_START = "ADD_WAREHOUSE_START"
    export const ADD_WAREHOUSE_SUCCESS = "ADD_WAREHOUSE_SUCCESS"
    export const ADD_WAREHOUSE_FAIL = "ADD_WAREHOUSE_FAIL"

    // Category
    export const GET_CATEGORY = "GET_CATEGORY"

    export const ADD_CATEGORY_START = "ADD_CATEGORY_START"
    export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
    export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"

    // Sub Category
    export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

// Product
    export const GET_PRODUCT_START = "GET_PRODUCT_START"
    export const GET_PRODUCT = "GET_PRODUCT"

    export const ADD_PRODUCT_START = "ADD_PRODUCT_START"
    export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
    export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

    export const UPLOAD_PRODUCT_IMAGE_START = "UPLOAD_PRODUCT_IMAGE_START"
    export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS"
    export const UPLOAD_PRODUCT_IMAGE_FAIL = "UPLOAD_PRODUCT_IMAGE_FAIL"
    export const DELETE_IMAGE_PRODUCT = 'DELETE_IMAGE_PRODUCT';

// Payment Confirmation
    export const GET_PAYMENT_CONFIRMATION = "GET_PAYMENT_CONFIRMATION"

    export const UPDATE_STATUS_CONFIRMATION_START = "UPDATE_STATUS_CONFIRMATION_START"
    export const UPDATE_STATUS_CONFIRMATION_SUCCESS = "UPDATE_STATUS_CONFIRMATION_SUCCESS"
    export const UPDATE_STATUS_CONFIRMATION_FAIL = "UPDATE_STATUS_CONFIRMATION_FAIL"

    export const UPDATE_STATUS_SENDING_START = "UPDATE_STATUS_SENDING_START"
    export const UPDATE_STATUS_SENDING_SUCCESS = "UPDATE_STATUS_SENDING_SUCCESS"
    export const UPDATE_STATUS_SENDING_FAIL = "UPDATE_STATUS_SENDING_FAIL"

    export const UPDATE_STATUS_ABORT_START = "UPDATE_STATUS_ABORT_START"
    export const UPDATE_STATUS_ABORT_SUCCESS = "UPDATE_STATUS_ABORT_SUCCESS"
    export const UPDATE_STATUS_ABORT_FAIL = "UPDATE_STATUS_ABORT_FAIL"
    