export { default as Dashboard } from './Dashboard';
export { default as Profile } from './Profile';
export { default as Home } from './Home'
export { default as Warehouse } from './Master/Warehouse'
export { default as CreateWarehouse } from './Master/Warehouse/CreateWarehouse'
export { default as Category } from './Master/Category'
export { default as CreateCategory } from './Master/Category/CreateCategory'
export { default as EditCategory } from './Master/Category/EditCategory'
export { default as Product } from './Product'
export { default as CraeteProduct } from './Product/CreateProduct'
export { default as EditProduct } from './Product/EditProduct'
export { default as PaymentConfirmation } from './PaymentConfirmation'