export { default as StockProduct1 } from './StockProduct1'
export { default as StockProduct2 } from './StockProduct2'
export { default as StockProduct3 } from './StockProduct3'
export { default as StockProduct4 } from './StockProduct4'
export { default as StockProduct5 } from './StockProduct5'
export { default as StockProduct6 } from './StockProduct6'